name: ✨ Feature Request
description: Suggest a new feature or improvement for Retina Result Fetcher
title: "[Feature]: "
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please describe your idea in detail below.

  - type: textarea
    id: problem
    attributes:
      label: Problem or limitation
      description: Is your feature request related to a problem? Please describe.
      placeholder: |
        Example:
        "I'm always frustrated when I have to manually check each student's results one by one..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe what you want to happen.
      placeholder: |
        Example:
        "It would be great if there was a batch processing mode that could fetch results for all students at once..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: |
        Example:
        "I thought about writing a custom script, but having it built-in would be more convenient for all users..."

  - type: dropdown
    id: feature-area
    attributes:
      label: Which area does this feature relate to?
      multiple: true
      options:
        - "User Interface/UX"
        - "Result Display"
        - "Comparison Features"
        - "Student Management"
        - "Data Export/Import"
        - "Performance/Speed"
        - "Authentication/Login"
        - "Error Handling"
        - "Mobile App Features"
        - "Termux Integration"
        - "Documentation"
        - "Other"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: How important is this feature to you?
      options:
        - "Critical - I need this to use the tool effectively"
        - "High - This would significantly improve my workflow"
        - "Medium - Nice to have, but not essential"
        - "Low - Minor improvement, but still useful"

  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: |
        How would you use this feature?
        Who would benefit from it? (e.g., individual students, groups, tutors)
      placeholder: |
        Example:
        "As a student, I would use this feature to quickly compare my progress with my study group..."
      validations:
        required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or examples
      description: |
        If you have any mockups, screenshots, or examples of similar features in other software, please share them.
        
        **Tip:** You can attach files by dragging and dropping or clicking this area.

  - type: textarea
    id: technical-details
    attributes:
      label: Technical considerations (optional)
      description: |
        Any technical details, API considerations, or implementation thoughts?
        
        Are there any Retina API limitations to consider?
      placeholder: |
        Example:
        "The Retina API currently doesn't provide this data, but we could calculate it from existing information..."

  - type: textarea
    id: related-features
    attributes:
      label: Related features
      description: |
        Does this feature relate to any existing features?
        Would it replace or enhance any current functionality?
      placeholder: |
        Example:
        "This would enhance the 'Compare Results' feature by adding statistical analysis..."

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context, screenshots, or examples about the feature request here.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues and verified this is not a duplicate
          required: true
        - label: I have provided a clear, descriptive title
          required: true
        - label: I have explained the problem and proposed solution in detail
          required: true
        - label: I understand this is an unofficial project and feature requests depend on volunteer availability
          required: true
        - label: I'm willing to help test the feature if implemented
        - label: I'm open to discussing implementation details or alternatives
